# String Formatting (Interactive)

This is an interactive tutorial. You can click the rocket -> binder link at the top of this page to interact with the code and outputs below.

## Why Format

Often string formatting is used to truncate part of a string or round floating point numbers to a desired precision. All of the techniques below use a special shorthand for specifying the formatting desired.

For example:

To round pi to 4 decimal points, we would use the float formatter, `f` and specify `.4` decimal places. This will round to the number of decimal places specified.

In [1]:
pi = 3.14159265
print("Pi is %.4f" % pi)

Pi is 3.1416

To specify a certain number of characters width, you can also put a number before the decimal point in the format code.

For example:

To print the following lines as 10 characters each, we would specify `%10.f` as the format code and Python will automatically add spaced in front to make the output 10 characters long:

In [2]:
print("%10.f" % 1)
print("%10.f" % 10)
print("%10.f" % 100)
print("%10.f" % 1000)
print("%10.f" % 10000)

         1
        10
       100
      1000
     10000

## Three types of string formatting

Python allows you to specify how to format strings in 3 ways:

* The Old school (% operator): `" "%()`
* The `.format()` method: `" ".format()`
* With an f-string (Python version > 3.6 only): `f" "`

Useful sites:

- Python string docs [link](https://docs.python.org/3/library/string.html)
- Using % and .format(): [link](https://pyformat.info)
- Python f-strings [link](http://zetcode.com/python/fstring/)

## Old school (%)

Below we use the `%` operator after the string to include the three elements into the three locations denoted by `%` within the string.

We use three different format codes for the three numbers included in the string:

- The integer format code `d`
- The float format code rounding to a whole number `.0f` 
- The float format code rounding to 2 decimal places `.2f`.

Note: To print a regular %, you need to type two %% in a row when using the `%` operator.

In [3]:
discount = 30  # %
price = 499.99
new_price = price * (1-discount/100)

print("SALE: Get %d%% off the new PS5 and pay $%.0f instead of $%.2f." % 
      (discount, new_price, price))

SALE: Get 30% off the new PS5 and pay $350 instead of $499.99.

## Format method (.format())

The format method inserts each element in the parentheses of `.format()`, into the brackets in the string. The same format codes used above are included after the colon in each set of brackets `"{:fmt}"`.

In [4]:
print("SALE: Get {:d}% off the new PS5 and pay ${:.0f} instead of ${:.2f}."
      .format(discount, new_price, price))

SALE: Get 30% off the new PS5 and pay $350 instead of $499.99.

## F-string (f'')

The f-string allows us to include the element in place in the string instead of in a list at the end. This can make it easier to read which values are being inserted into which parts of the string. The syntax is `{value:fmt}` with the value being specified before the colon and the format code after the colon in the `{}` brackets.

In [5]:
print(f"SALE: Get {discount:d}% off the new PS5 and pay ${new_price:.0f} instead of ${price:.2f}.")

SALE: Get 30% off the new PS5 and pay $350 instead of $499.99.

## String formatting with loop

We can loop through the following two lists of values and print each pair with a format string.

In [2]:
month   = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
balance = [-10.45,  50.99,  0.99,  -5.76,  100.57, -78.22]

print('Monthly Balance')
for mo, bal in zip(month, balance):
    print(f'We have ${bal:.2f} left in {mo}.')

Monthly Balance
We have $-10.45 left in Jan.
We have $50.99 left in Feb.
We have $0.99 left in Mar.
We have $-5.76 left in Apr.
We have $100.57 left in May.
We have $-78.22 left in Jun.

This looks a little messy. We can clean up our output by:

- Specifying the width of the number field. Since the longest output is 6 characters, we can use the code `6.2f` to have Python pad all of the numbers to 6 characters long
- We can also make a 30-character underline with the `-^30` short hand.

In [7]:
# Monthly Balance is centered on a 30 char line of ---
print('{:-^30}'.format('Monthly Balance'))

for mo, bal in zip(month, balance):
    print(f'We have $ {bal:6.2f} left in {mo}.')

# Here we can make a 30 char line of ===
print(f'{"":=^30}')
print('Total balance for the first {} months was $ {:.2f}'.format(len(month), sum(balance)))

-------Monthly Balance--------
We have $ -10.45 left in Jan.
We have $  50.99 left in Feb.
We have $   0.99 left in Mar.
We have $  -5.76 left in Apr.
We have $ 100.57 left in May.
We have $ -78.22 left in Jun.
==============================
Total balance for the first 6 months was $ 58.12

## Practice: multiplication table

Try to exactly reproduce the table below by using a loop, print statements and string format codes.

Note: Pay attention to spacing, zeros in front of the single digit numbers, and the horizontal and vertical lines

```{code-block}
01  |02  03  04  05  06  07  08  09  
------------------------------------
02  |04  06  08  10  12  14  16  18  
03  |06  09  12  15  18  21  24  27  
04  |08  12  16  20  24  28  32  36  
05  |10  15  20  25  30  35  40  45  
06  |12  18  24  30  36  42  48  54  
07  |14  21  28  35  42  49  56  63  
08  |16  24  32  40  48  56  64  72  
09  |18  27  36  45  54  63  72  81  
```

```{admonition} Click the button to reveal ONE of the answers!
:class: dropdown

```{code-block} python
import numpy as np
for i in range(1,10):
    j = np.arange(1,10)

    for idx, ans in enumerate(i*j):
        if idx!=8:
            print(f'{ans:02d}  ', end='')
        else:
            print(f'{ans:02d}  ')
    
        if idx==0:
            print('|', end='')
            
    if i == 1:
        print('{}'.format('-'*(4*9)) )
```
```

In [12]:
# Create your multiplication table here!
import numpy as np
for i in range(1,10):
    j = np.arange(1,10)
    print(i)
    print(j)
    for item in enumerate(i*j):
        print(item)
        print(item[0])
        print(item[1])

    for idx, ans in enumerate(i*j):
        print(f"idx={idx}, ans={ans}")
        if idx!=8:
            print(f'{ans:02d}  ', end='')
        else:
            print(f'{ans:02d}  ')
    
        if idx==0:
            print('|', end='')
            
    if i == 1:
        print('{}'.format('-'*(4*9)) )

1
[1 2 3 4 5 6 7 8 9]
(0, 1)
0
1
(1, 2)
1
2
(2, 3)
2
3
(3, 4)
3
4
(4, 5)
4
5
(5, 6)
5
6
(6, 7)
6
7
(7, 8)
7
8
(8, 9)
8
9
idx=0, ans=1
01  |idx=1, ans=2
02  idx=2, ans=3
03  idx=3, ans=4
04  idx=4, ans=5
05  idx=5, ans=6
06  idx=6, ans=7
07  idx=7, ans=8
08  idx=8, ans=9
09
------------------------------------
2
[1 2 3 4 5 6 7 8 9]
(0, 2)
0
2
(1, 4)
1
4
(2, 6)
2
6
(3, 8)
3
8
(4, 10)
4
10
(5, 12)
5
12
(6, 14)
6
14
(7, 16)
7
16
(8, 18)
8
18
idx=0, ans=2
02  |idx=1, ans=4
04  idx=2, ans=6
06  idx=3, ans=8
08  idx=4, ans=10
10  idx=5, ans=12
12  idx=6, ans=14
14  idx=7, ans=16
16  idx=8, ans=18
18
3
[1 2 3 4 5 6 7 8 9]
(0, 3)
0
3
(1, 6)
1
6
(2, 9)
2
9
(3, 12)
3
12
(4, 15)
4
15
(5, 18)
5
18
(6, 21)
6
21
(7, 24)
7
24
(8, 27)
8
27
idx=0, ans=3
03  |idx=1, ans=6
06  idx=2, ans=9
09  idx=3, ans=12
12  idx=4, ans=15
15  idx=5, ans=18
18  idx=6, ans=21
21  idx=7, ans=24
24  idx=8, ans=27
27
4
[1 2 3 4 5 6 7 8 9]
(0, 4)
0
4
(1, 8)
1
8
(2, 12)
2
12
(3, 16)
3
16
(4, 20)
4
20
(5, 24)
5
24
(6, 28)
6
28
(7, 32)
7
32
(8, 36)
8
36
idx=0, ans=4
04  |idx=1, ans=8
08  idx=2, ans=12
12  idx=3, ans=16
16  idx=4, ans=20
20  idx=5, ans=24
24  idx=6, ans=28
28  idx=7, ans=32
32  idx=8, ans=36
36
5
[1 2 3 4 5 6 7 8 9]
(0, 5)
0
5
(1, 10)
1
10
(2, 15)
2
15
(3, 20)
3
20
(4, 25)
4
25
(5, 30)
5
30
(6, 35)
6
35
(7, 40)
7
40
(8, 45)
8
45
idx=0, ans=5
05  |idx=1, ans=10
10  idx=2, ans=15
15  idx=3, ans=20
20  idx=4, ans=25
25  idx=5, ans=30
30  idx=6, ans=35
35  idx=7, ans=40
40  idx=8, ans=45
45
6
[1 2 3 4 5 6 7 8 9]
(0, 6)
0
6
(1, 12)
1
12
(2, 18)
2
18
(3, 24)
3
24
(4, 30)
4
30
(5, 36)
5
36
(6, 42)
6
42
(7, 48)
7
48
(8, 54)
8
54
idx=0, ans=6
06  |idx=1, ans=12
12  idx=2, ans=18
18  idx=3, ans=24
24  idx=4, ans=30
30  idx=5, ans=36
36  idx=6, ans=42
42  idx=7, ans=48
48  idx=8, ans=54
54
7
[1 2 3 4 5 6 7 8 9]
(0, 7)
0
7
(1, 14)
1
14
(2, 21)
2
21
(3, 28)
3
28
(4, 35)
4
35
(5, 42)
5
42
(6, 49)
6
49
(7, 56)
7
56
(8, 63)
8
63
idx=0, ans=7
07  |idx=1, ans=14
14  idx=2, ans=21
21  idx=3, ans=28
28  idx=4, ans=35
35  idx=5, ans=42
42  idx=6, ans=49
49  idx=7, ans=56
56  idx=8, ans=63
63
8
[1 2 3 4 5 6 7 8 9]
(0, 8)
0
8
(1, 16)
1
16
(2, 24)
2
24
(3, 32)
3
32
(4, 40)
4
40
(5, 48)
5
48
(6, 56)
6
56
(7, 64)
7
64
(8, 72)
8
72
idx=0, ans=8
08  |idx=1, ans=16
16  idx=2, ans=24
24  idx=3, ans=32
32  idx=4, ans=40
40  idx=5, ans=48
48  idx=6, ans=56
56  idx=7, ans=64
64  idx=8, ans=72
72
9
[1 2 3 4 5 6 7 8 9]
(0, 9)
0
9
(1, 18)
1
18
(2, 27)
2
27
(3, 36)
3
36
(4, 45)
4
45
(5, 54)
5
54
(6, 63)
6
63
(7, 72)
7
72
(8, 81)
8
81
idx=0, ans=9
09  |idx=1, ans=18
18  idx=2, ans=27
27  idx=3, ans=36
36  idx=4, ans=45
45  idx=5, ans=54
54  idx=6, ans=63
63  idx=7, ans=72
72  idx=8, ans=81
81